#!/usr/bin/env bash
set -euo pipefail

RUN_DOCKER=true
INTERACTIVE_ENV=false

# ------------------------------------------
# Helpers
# ------------------------------------------
read_default() {
  local prompt="$1"
  local default="$2"
  local reply=""
  read -r -p "$prompt [$default]: " reply
  echo "${reply:-$default}"
}

gen_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 24 | tr -d '/+=' | head -c 24
  else
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24
  fi
}

detect_host_ip() {
  hostname -I 2>/dev/null | awk '{print $1}' || echo "<VM_IP>"
}

generate_env_interactive() {
  echo
  if [ "${1:-}" = "overwrite" ]; then
    echo "📝 Reconfiguring .env (overwrite)"
  else
    echo "📝 Starting interactive setup"
  fi
  echo "   (Press Enter to accept defaults shown in brackets)"
  echo

  local data_base app_user root_pw app_pw
  data_base="$(read_default "Data directory base" "/var/lib/database-docker")"
  app_user="$(read_default "Application username" "momod")"

  echo
  read -r -p "Auto-generate secure passwords? [Y/n]: " auto_pw
  if [[ ! "$auto_pw" =~ ^[Nn]$ ]]; then
    root_pw="$(gen_password)"
    app_pw="$(gen_password)"
    echo "   ✓ Passwords generated automatically"
  else
    root_pw="$(read_default "Root/superuser password" "changeme-root")"
    app_pw="$(read_default "Application user password" "changeme-app")"
  fi

  local mysql_port=3306 mariadb_port=3307 postgres_port=5432 pgbouncer_port=6432
  local mysql_tz="Asia/Jakarta" mariadb_tz="Asia/Jakarta" postgres_tz="UTC"

  if [ "$USE_MYSQL" = true ]; then
    echo
    echo "--- MySQL ---"
    mysql_port="$(read_default "MySQL host port (accessible from other VMs)" "$mysql_port")"
    mysql_tz="$(read_default "MySQL timezone" "$mysql_tz")"
  fi

  if [ "$USE_MARIADB" = true ]; then
    echo
    echo "--- MariaDB ---"
    mariadb_port="$(read_default "MariaDB host port (accessible from other VMs)" "$mariadb_port")"
    mariadb_tz="$(read_default "MariaDB timezone" "$mariadb_tz")"
  fi

  if [ "$USE_POSTGRES" = true ]; then
    echo
    echo "--- PostgreSQL + PgBouncer ---"
    postgres_port="$(read_default "PostgreSQL direct port" "$postgres_port")"
    pgbouncer_port="$(read_default "PgBouncer port (recommended for apps)" "$pgbouncer_port")"
    postgres_tz="$(read_default "PostgreSQL timezone" "$postgres_tz")"
  fi

  cat > .env <<EOF
# Generated by setup.sh on $(date -Iseconds)
# Host ports below are exposed on this VM for remote access from other machines.

# ===============================
# MYSQL
# ===============================
MYSQL_HOST_PORT=${mysql_port}
MYSQL_ROOT_PASSWORD=${root_pw}
MYSQL_USER=${app_user}
MYSQL_PASSWORD=${app_pw}
MYSQL_TZ=${mysql_tz}
MYSQL_DATA_PATH=${data_base}/mysql/data

# ===============================
# MARIADB
# ===============================
MARIADB_HOST_PORT=${mariadb_port}
MARIADB_ROOT_PASSWORD=${root_pw}
MARIADB_USER=${app_user}
MARIADB_PASSWORD=${app_pw}
MARIADB_TZ=${mariadb_tz}
MARIADB_DATA_PATH=${data_base}/mariadb/data

# ===============================
# POSTGRESQL
# ===============================
POSTGRES_HOST_PORT=${postgres_port}
POSTGRES_USER_APP=${app_user}
POSTGRES_PASSWORD_APP=${app_pw}
POSTGRES_ROOT_PASSWORD=${root_pw}
POSTGRES_TZ=${postgres_tz}
POSTGRES_DATA_PATH=${data_base}/postgre/data

# ===============================
# PGBOUNCER
# ===============================
PGBOUNCER_PORT=${pgbouncer_port}
PGBOUNCER_POOL_MODE=transaction
PGBOUNCER_MAX_CLIENT_CONN=200
PGBOUNCER_DEFAULT_POOL_SIZE=20
PGBOUNCER_AUTH_USER=postgres
PGBOUNCER_AUTH_PASSWORD=${root_pw}
PGBOUNCER_APP_USER=${app_user}
PGBOUNCER_APP_PASSWORD=${app_pw}
EOF

  chmod 600 .env
  INTERACTIVE_ENV=true

  echo
  echo "✅ .env created at $(pwd)/.env"
}

ensure_env() {
  if [ -f .env ]; then
    echo
    echo "⚠️  .env already exists at $(pwd)/.env"
    read -r -p "Overwrite and reconfigure? [y/N]: " overwrite_reply
    if [[ "$overwrite_reply" =~ ^[Yy]$ ]]; then
      cp .env ".env.bak.$(date +%Y%m%d%H%M%S)"
      echo "   ℹ️  Previous .env backed up"
      generate_env_interactive overwrite
    else
      echo "ℹ️  Keeping existing .env"
    fi
  else
    generate_env_interactive
  fi
}

print_remote_access_info() {
  local host_ip
  host_ip="$(detect_host_ip)"

  echo
  echo "========================================="
  echo " Remote Access (from other VMs)"
  echo "========================================="
  echo "  VM IP: ${host_ip}"
  echo

  if [ "$USE_MYSQL" = true ]; then
    echo "  MySQL:      ${host_ip}:${MYSQL_HOST_PORT}  user=${MYSQL_USER}"
  fi
  if [ "$USE_MARIADB" = true ]; then
    echo "  MariaDB:    ${host_ip}:${MARIADB_HOST_PORT}  user=${MARIADB_USER}"
  fi
  if [ "$USE_POSTGRES" = true ]; then
    echo "  PostgreSQL: ${host_ip}:${POSTGRES_HOST_PORT}  user=${POSTGRES_USER_APP}"
    echo "  PgBouncer:  ${host_ip}:${PGBOUNCER_PORT}  user=${POSTGRES_USER_APP}  (recommended for apps)"
  fi

  echo
  echo "  Open firewall on this VM (example):"
  [ "$USE_MYSQL" = true ] && echo "    sudo ufw allow ${MYSQL_HOST_PORT}/tcp"
  [ "$USE_MARIADB" = true ] && echo "    sudo ufw allow ${MARIADB_HOST_PORT}/tcp"
  [ "$USE_POSTGRES" = true ] && echo "    sudo ufw allow ${POSTGRES_HOST_PORT}/tcp"
  [ "$USE_POSTGRES" = true ] && echo "    sudo ufw allow ${PGBOUNCER_PORT}/tcp"
  echo
  echo "  Edit .env anytime, then: docker compose up -d"
}

# ------------------------------------------
# Engine selection flags
# ------------------------------------------
USE_POSTGRES=false
USE_MYSQL=false
USE_MARIADB=false
ENGINE_FLAGS=false

for arg in "$@"; do
  case $arg in
    --postgres|--mysql|--mariadb)
      ENGINE_FLAGS=true
      ;;
  esac
done

if [ "$ENGINE_FLAGS" = false ] && [ "$#" -eq 0 ]; then
  USE_POSTGRES=true
  USE_MYSQL=true
  USE_MARIADB=true
else
  for arg in "$@"; do
    case $arg in
      --no-run)
        RUN_DOCKER=false
        ;;
      --postgres)
        USE_POSTGRES=true
        ;;
      --mysql)
        USE_MYSQL=true
        ;;
      --mariadb)
        USE_MARIADB=true
        ;;
      --help|-h)
        cat <<'HELP'
Usage: ./setup.sh [options]

Options:
  --postgres   Install PostgreSQL (+ PgBouncer)
  --mysql      Install MySQL
  --mariadb    Install MariaDB
  --no-run     Prepare directories only, skip Docker
  -h, --help   Show this help

If .env does not exist, an interactive wizard runs automatically.
If .env already exists, you will be asked whether to overwrite it.
Examples:
  ./setup.sh --postgres          # PostgreSQL only, interactive .env
  ./setup.sh --mysql --mariadb   # MySQL + MariaDB
  ./setup.sh                     # All engines (default)
HELP
        exit 0
        ;;
      *)
        echo "❌ Unknown option: $arg"
        echo "   Run ./setup.sh --help"
        exit 1
        ;;
    esac
  done
fi

# Interactive engine selection when no .env and no engine flags
if [ ! -f .env ] && [ "$ENGINE_FLAGS" = false ]; then
  echo
  echo "Which database engines do you want?"
  echo "  1) PostgreSQL only (+ PgBouncer)"
  echo "  2) MySQL only"
  echo "  3) MariaDB only"
  echo "  4) All engines"
  echo "  5) Custom (enter numbers separated by space, e.g. 1 2)"
  engine_choice="$(read_default "Choice" "4")"

  USE_POSTGRES=false
  USE_MYSQL=false
  USE_MARIADB=false

  case "$engine_choice" in
    1) USE_POSTGRES=true ;;
    2) USE_MYSQL=true ;;
    3) USE_MARIADB=true ;;
    4) USE_POSTGRES=true; USE_MYSQL=true; USE_MARIADB=true ;;
    *)
      for n in $engine_choice; do
        case $n in
          1) USE_POSTGRES=true ;;
          2) USE_MYSQL=true ;;
          3) USE_MARIADB=true ;;
        esac
      done
      ;;
  esac

  if [ "$USE_POSTGRES" = false ] && [ "$USE_MYSQL" = false ] && [ "$USE_MARIADB" = false ]; then
    echo "❌ No engine selected"
    exit 1
  fi
fi

echo "========================================="
echo " Database Stack Initial Setup"
echo "========================================="

if [ "$USE_POSTGRES" = true ]; then echo "  • PostgreSQL + PgBouncer"; fi
if [ "$USE_MYSQL" = true ]; then echo "  • MySQL"; fi
if [ "$USE_MARIADB" = true ]; then echo "  • MariaDB"; fi

# ------------------------------------------
# Ensure .env exists (interactive if missing or on overwrite)
# ------------------------------------------
ensure_env

set -a
source .env
set +a

# ------------------------------------------
# Validate required variables dynamically
# ------------------------------------------
REQUIRED_VARS=()

[ "$USE_MYSQL" = true ] && REQUIRED_VARS+=(MYSQL_DATA_PATH)
[ "$USE_MARIADB" = true ] && REQUIRED_VARS+=(MARIADB_DATA_PATH)
[ "$USE_POSTGRES" = true ] && REQUIRED_VARS+=(POSTGRES_DATA_PATH)

for VAR in "${REQUIRED_VARS[@]}"; do
  if [ -z "${!VAR:-}" ]; then
    echo "❌ Environment variable $VAR is not set"
    exit 1
  fi
done

# ------------------------------------------
# Create directories
# ------------------------------------------
echo
echo "📁 Creating persistent data directories..."

[ "$USE_MYSQL" = true ] && mkdir -p "$MYSQL_DATA_PATH"
[ "$USE_MARIADB" = true ] && mkdir -p "$MARIADB_DATA_PATH"
[ "$USE_POSTGRES" = true ] && mkdir -p "$POSTGRES_DATA_PATH"

# ------------------------------------------
# Fix ownership
# ------------------------------------------
echo
echo "🔐 Fixing ownership..."

if [ "$USE_MYSQL" = true ]; then
  sudo chown -R 999:999 "$(dirname "$MYSQL_DATA_PATH")"
  sudo chmod 750 "$MYSQL_DATA_PATH"
fi

if [ "$USE_MARIADB" = true ]; then
  sudo chown -R 999:999 "$(dirname "$MARIADB_DATA_PATH")"
  sudo chmod 750 "$MARIADB_DATA_PATH"
fi

if [ "$USE_POSTGRES" = true ]; then
  sudo chown -R 999:999 "$(dirname "$POSTGRES_DATA_PATH")"
  sudo chmod 700 "$POSTGRES_DATA_PATH"
fi

# ------------------------------------------
# Ensure executable scripts
# ------------------------------------------
echo
echo "🔧 Ensuring executable scripts..."

[ -d "./mysql/init" ] && chmod +x ./mysql/init/*.sh 2>/dev/null || true
[ -d "./mariadb/init" ] && chmod +x ./mariadb/init/*.sh 2>/dev/null || true
[ -d "./postgres/init" ] && chmod +x ./postgres/init/*.sh 2>/dev/null || true
[ -f "./pgbouncer/entrypoint.sh" ] && chmod +x ./pgbouncer/entrypoint.sh
[ -f "./reset-databases.sh" ] && chmod +x ./reset-databases.sh
[ -f "./scripts/mysql-make-superadmin.sh" ] && chmod +x ./scripts/mysql-make-superadmin.sh
[ -f "./scripts/mariadb-make-superadmin.sh" ] && chmod +x ./scripts/mariadb-make-superadmin.sh

# ------------------------------------------
# Fix stale shared-net (manual create vs Compose-managed)
# ------------------------------------------
fix_shared_net() {
  if ! docker network inspect shared-net >/dev/null 2>&1; then
    return 0
  fi

  local label containers
  label="$(docker network inspect shared-net --format '{{index .Labels "com.docker.compose.network"}}' 2>/dev/null || true)"
  containers="$(docker network inspect shared-net --format '{{len .Containers}}' 2>/dev/null || echo "0")"

  if [ "$label" = "shared-net" ]; then
    return 0
  fi

  echo
  echo "⚠️  Network 'shared-net' exists but was created outside Compose (label mismatch)."
  echo "   This can happen if the network was created manually with 'docker network create'."

  if [ "$containers" != "0" ]; then
    echo
    echo "   Containers are still attached. Stop them first, then recreate the network:"
    echo "     docker compose down"
    echo "     docker network rm shared-net"
    echo "     ./setup.sh"
    exit 1
  fi

  echo "   No containers attached — removing old network (Compose will recreate it)..."
  docker network rm shared-net
}

# ------------------------------------------
# Docker
# ------------------------------------------
if [ "$RUN_DOCKER" = true ]; then
  fix_shared_net
  echo
  echo "🐳 Building selected services..."

  SERVICES=()

  if [ "$USE_MYSQL" = true ]; then
    SERVICES+=(mysql)
  fi

  if [ "$USE_MARIADB" = true ]; then
    SERVICES+=(mariadb)
  fi

  if [ "$USE_POSTGRES" = true ]; then
    SERVICES+=(postgres pgbouncer) # auto include pgbouncer
  fi

  docker compose build "${SERVICES[@]}"
  docker compose up -d "${SERVICES[@]}"

  sleep 5

  # Post start scripts
  if [ "$USE_MYSQL" = true ]; then
    docker exec mysql_db bash /scripts/mysql-make-superadmin.sh || true
  fi

  if [ "$USE_MARIADB" = true ]; then
    docker exec mariadb_db bash /scripts/mariadb-make-superadmin.sh || true
  fi

  echo
  echo "✅ Setup complete."
  print_remote_access_info
else
  echo
  echo "ℹ️  Setup complete. Docker skipped (--no-run)."
  print_remote_access_info
fi